version: "3.9"

services:
  telefone_sync:
    container_name: telefone_sync
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./sync_telefones.log:/app/sync_telefones.log
    tty: true
